name: ðŸª© 3D GitHub Profile

on:
  schedule: [{cron: "0 0 * * *"}]  # Cada 24 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate 3D profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Smith-Sr
          config: config.yml
