name: 游뿛 Update 3D Profile

on:
  schedule:
    - cron: "0 0 * * *"  # se actualiza todos los d칤as a medianoche
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 游빌 Clonar el repositorio
        uses: actions/checkout@v4

      - name: 游깳 Descargar gr치fico 3D de contribuciones
        run: |
          mkdir -p profile-3d-contrib
          curl -L "https://raw.githubusercontent.com/yoshi389111/github-profile-3d-contrib/main/docs/demo/profile-night-rainbow.svg" -o profile-3d-contrib/smith-3d.svg

      - name: 游 Subir cambios al repositorio
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "游댃 Actualizaci칩n autom치tica del gr치fico 3D"
          git push
