name: Metrics
on:
  # Ejecutar autom치ticamente cada d칤a a las 00:00 UTC
  schedule: [{cron: "0 0 * * *"}]
  # Permitir ejecuci칩n manual
  workflow_dispatch:
  # Ejecutar cuando se haga push
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Opciones generales
          user: Smith-Sr
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Lima
          
          # 游꿛 Plugins activados
          
          # L칤neas de c칩digo agregadas/eliminadas
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          # Lenguajes m치s usados
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          # Actividad reciente
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          # Commits notables
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          
          # Repositorios destacados
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          
          # Calendario de contribuciones (isom칠trico)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # H치bitos de c칩digo
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          
          # Stars en el tiempo
          plugin_starlists: yes
          plugin_starlists_limit: 2
          plugin_starlists_limit_repositories: 2
          plugin_starlists_shuffle_repositories: yes
          
          # Tr치fico del repositorio
          plugin_traffic: yes
          
          # Seguidores
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
