name: Generate profile-3d-contrib
on:
  schedule:
    - cron: "0 0 * * *"   # opcional: lo ejecuta cada d√≠a
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate 3D profile contrib
        uses: yoshi389111/github-profile-3d-contrib@v0.7.1
        with:
          USERNAME: Smith-Sr
          # Opcionales: THEME, ANIMATION, etc. revisa la doc del action
